---
- name: Install Python and Flask
  hosts: web-servers
  become: yes

  tasks:
    - name: Copy app files to remote folder
      ansible.builtin.copy:
        src: /path/pyapp/
        dest: /tmp/app/
        remote_src: yes
